🚧 e2136ページを追加
NITACwpl/astro-github-dojo pull request #5
Opened 2023-11-09 08:05 UTC by QwerTayu

e2136ページおなしゃす

2023-11-09 10:16 UTC, hengin-eer requested changes
リンク先だけ修正してね

2023-11-09 10:16 UTC, hengin-eer commented on src/components/MainTabular.astro
> +            <a href="./e2136">01</a>
これやと無限に`/e2126/e2126/...`ってなる
`/e2126`に直そう！

2023-11-10 08:27 UTC, QwerTayu commented on src/components/MainTabular.astro
> +            <a href="./e2136">01</a>
まじっすかおｋ

2023-11-10 08:51 UTC, hengin-eer approved these changes
👍

2023-11-10 08:51 UTC, merged